In [1]:
# 自定义层
# 构造一个没有任何参数的自定义层
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [2]:
# 将层作为组件合并到构建更复杂的模型中
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-6.2864e-09, grad_fn=<MeanBackward0>)

In [3]:
# 带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):  # 两个参数：输入维度、输出维度
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.0917, -0.5275, -0.7395],
        [-0.5555,  0.3398, -0.4171],
        [ 1.2797,  0.7959, -0.7569],
        [ 1.6222,  0.5235, -0.4801],
        [-1.6263,  0.4552, -0.6649]], requires_grad=True)

In [7]:
# 使用自定义层直接执行正向传播计算
linear(torch.rand(2, 5))

tensor([[0.2732, 0.9868, 0.0000],
        [0.0000, 1.4875, 0.0000]])

In [5]:
# 使用自定义层构建模型
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[5.6386],
        [3.8033]])